#!/usr/bin/env python3
"""Generate a deploy.sh script from an LQN model for K8s deployment + load testing.

Generates a self-contained bash script with commands:
  deploy.sh up    — create namespace, apply manifests, wait for pods
  deploy.sh down  — delete namespace
  deploy.sh test  — run Locust as K8s Job (headless, in-cluster)

Usage:
    python tools/deploy_gen.py model.lqn --image bistrulli/generic-microservice-tester:latest
    python tools/deploy_gen.py model.lqn -o deploy.sh
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    from gmt.lqn_parser import parse_lqn_file
    from gmt.tools.lqn_compiler import compile_model
    from gmt.tools.locustfile_gen import generate_locustfile
except ImportError:
    sys.path.insert(0, str(Path(__file__).parent.parent / "src"))
    sys.path.insert(0, str(Path(__file__).parent))
    from lqn_parser import parse_lqn_file
    from lqn_compiler import compile_model
    from locustfile_gen import generate_locustfile


def _sanitize_name(name: str) -> str:
    """Convert model name to a K8s-safe namespace suffix."""
    return name.lower().replace("_", "-").replace(" ", "-").replace(".", "-")


def generate_deploy_script(
    model_path: str,
    image: str = "bistrulli/generic-microservice-tester:latest",
    namespace: str | None = None,
    node_port: int | None = None,
) -> tuple[str, str]:
    """Generate a deploy.sh script and locustfile for a given LQN model.

    The script embeds K8s manifests inline. The locustfile is a separate file
    written alongside the deploy script.

    Args:
        model_path: Path to the .lqn model file.
        image: Docker image for GMT containers.
        namespace: K8s namespace (default: gmt-<model_name>).
        node_port: Fixed NodePort for entry-point service (None = auto-assign).

    Returns:
        Tuple of (deploy_script, locustfile) as strings.
    """
    model = parse_lqn_file(model_path)

    if namespace is None:
        namespace = f"gmt-{_sanitize_name(model.name)}"

    # Generate K8s manifests (OTEL-compliant)
    manifests = compile_model(model, image=image, namespace=namespace, node_port=node_port)

    # Generate locustfile (stored as separate file alongside deploy.sh)
    locustfile = generate_locustfile(model)

    # Extract reference task info for Locust defaults
    ref_tasks = [t for t in model.tasks if t.is_reference]
    default_users = ref_tasks[0].multiplicity if ref_tasks else 1

    script = f'''#!/usr/bin/env bash
# Auto-generated deploy script for LQN model: {model.name}
# Generated by: lqn-deploy (GMT)
#
# Usage:
#   ./deploy.sh up                    — deploy to K8s
#   ./deploy.sh down                  — tear down
#   ./deploy.sh test [users] [duration] — run Locust load test in-cluster
set -euo pipefail

NAMESPACE="{namespace}"

# ─── Deploy ───────────────────────────────────────────────────────────
cmd_up() {{
    echo "=== Deploying {model.name} to namespace $NAMESPACE ==="

    echo "[1/5] Verifying observability stack..."
    if ! kubectl get namespace observability &>/dev/null; then
        echo "ERROR: namespace 'observability' not found. Deploy OTEL stack first."
        exit 1
    fi

    echo "[2/5] Creating namespace..."
    kubectl create namespace "$NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -

    echo "[3/5] Applying OTEL Instrumentation CR..."
    cat <<'INSTREOF' | kubectl apply -n "$NAMESPACE" -f -
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: python-instrumentation
spec:
  exporter:
    endpoint: http://otel-collector.observability:4317
  propagators:
  - tracecontext
  - baggage
  python:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:latest
INSTREOF

    echo "[4/5] Applying manifests..."
    cat <<'MANIFESTS' | kubectl apply -n "$NAMESPACE" -f -
{manifests}
MANIFESTS

    echo "[5/5] Waiting for pods to be ready..."
    sleep 3
    kubectl wait --for=condition=Ready pod --all -n "$NAMESPACE" --timeout=300s

    echo "=== Deploy complete: {model.name} in $NAMESPACE ==="
    kubectl get pods -n "$NAMESPACE"
}}

# ─── Teardown ─────────────────────────────────────────────────────────
cmd_down() {{
    echo "=== Tearing down $NAMESPACE ==="
    kubectl delete namespace "$NAMESPACE" --ignore-not-found --timeout=60s
    echo "=== Cleanup complete ==="
}}

# ─── Load Test ────────────────────────────────────────────────────────
cmd_test() {{
    local users="${{1:-{default_users}}}"
    local duration="${{2:-60s}}"

    echo "=== Running Locust load test: $users users, $duration ==="

    # Inject locustfile as ConfigMap (from file next to this script)
    SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
    kubectl create configmap gmt-locustfile -n "$NAMESPACE" \\
        --from-file=locustfile.py="$SCRIPT_DIR/locustfile.py" \\
        --dry-run=client -o yaml | kubectl apply -f -

    # Clean previous Job if exists
    kubectl delete job locust-loadtest -n "$NAMESPACE" --ignore-not-found 2>/dev/null

    # Create Locust Job
    cat <<JOBEOF | kubectl apply -n "$NAMESPACE" -f -
apiVersion: batch/v1
kind: Job
metadata:
  name: locust-loadtest
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: locust
        image: locustio/locust:2.32.6
        command: ["locust"]
        args:
        - "--headless"
        - "--users=$users"
        - "--spawn-rate=$users"
        - "--run-time=$duration"
        - "-f"
        - "/mnt/locustfile.py"
        volumeMounts:
        - name: locustfile
          mountPath: /mnt
      volumes:
      - name: locustfile
        configMap:
          name: gmt-locustfile
JOBEOF

    echo "Waiting for load test to complete..."
    kubectl wait --for=condition=complete job/locust-loadtest \\
        -n "$NAMESPACE" --timeout=600s

    echo ""
    echo "=== Locust Results ==="
    kubectl logs job/locust-loadtest -n "$NAMESPACE"
}}

# ─── Main ─────────────────────────────────────────────────────────────
case "${{1:-}}" in
    up)   cmd_up ;;
    down) cmd_down ;;
    test) shift; cmd_test "$@" ;;
    *)    echo "Usage: $0 up|down|test [users] [duration]"; exit 1 ;;
esac
'''

    return script, locustfile


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate deploy.sh script from LQN model"
    )
    parser.add_argument("lqn_file", help="Path to .lqn model file")
    parser.add_argument(
        "--image",
        default="bistrulli/generic-microservice-tester:latest",
        help="Docker image for GMT containers",
    )
    parser.add_argument("--namespace", help="K8s namespace (default: gmt-<model>)")
    parser.add_argument(
        "--nodeport", type=int, default=None,
        help="Fixed NodePort for entry-point service (default: K8s auto-assign)",
    )
    parser.add_argument("-o", "--output", help="Output file (default: stdout)")

    args = parser.parse_args()

    script, locustfile = generate_deploy_script(
        args.lqn_file, image=args.image, namespace=args.namespace,
        node_port=args.nodeport,
    )

    if args.output:
        out = Path(args.output)
        out.write_text(script)
        out.chmod(0o755)
        # Write locustfile alongside deploy.sh
        locust_path = out.parent / "locustfile.py"
        locust_path.write_text(locustfile)
        print(f"Written to {args.output} + {locust_path}", file=sys.stderr)
    else:
        print(script)


if __name__ == "__main__":
    main()
